
language: julia

os:
  - osx

julia:
  - 1.5
  - 1.6
  - 1.7

env:
  global:
    - PYTHON=''

notifications:
  email: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.7
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
